StoreApp/Models/Product.cs
namespace StoreApp.Models
{
    public class Product
    {
        public int Id { get; set; }
        public String? ProductName { get; set; } = String.Empty;
        public decimal Price { get; set; }

    }
}

StoreApp/Areas/Admin/Controllers/ProductController.cs
using Entities.Dtos;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;
        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }
        public IActionResult Index()
        {
            var model = _manager.ProductService.GetProducts(false);
            return View(model);
        }
        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetAllCategory(false), "CategoryId", "CategoryName", "1");
        }

        public IActionResult Create()
        {
            ViewBag.Categories = GetCategoriesSelectList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ProductDtoForInsertion prdDto, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //file operation
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                prdDto.ImageUrl = String.Concat("/images/", file.FileName);
                _manager.ProductService.CreateProduct(prdDto);
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Update([FromRoute(Name = "id")] int id)
        {
            ViewBag.Categories = GetCategoriesSelectList();
            var model = _manager.ProductService.GetOneProductForUpdate(id, false);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] ProductDtoForUpdate prdDto,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                prdDto.ImageUrl = String.Concat("/images/", file.FileName);
                _manager.ProductService.UpdateOneProduct(prdDto);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete([FromRoute(Name = "id")] int id)
        {
            _manager.ProductService.DeleteOneProduct(id);
            return RedirectToAction("Index");
        }
    }
}

StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;
        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }
        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetAllCategory(false);
            return View(categories);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;


namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetProducts(false);
            return View(model);
        }
        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

StoreApp/Views/Product/Get.cshtml
@using StoreApp.Infrastructe.Extensions
@model Product
<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <h6 class="display-6">
                @Model.ProductName
            </h6>
            <img class="img-fluid shadow my-3" src="@Model?.ImageUrl" alt="@Model?.ProductName" />
            <p class="lead text-danger">@Model.Price.ToString("c")</p>
            <div class="btn-group">
                <a class="btn btn-primary" asp-controller="Product" asp-action="Index">Products</a>
                <form id="@Model.ProductId" asp-page="/cart" method="post">
                    <input type="hidden" asp-for="ProductId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery();" />
                    <button type="submit" class="btn btn-outline-primary">
                        <i class="fa fa-cart-shopping"></i>
                    </button>
                </form>
                <a class="btn btn-outline-primary" asp-controller="Home" asp-action="Index">Home</a>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Product/Index.cshtml
@model IQueryable<Product>

<div class="row">
  <div class="col-md-3 my-4">
      @await Component.InvokeAsync("CategoriesMenu")
  </div>
  <div class="col-md-9">
     <div class="row my-3">
        @foreach (Product prd in Model)
        {
            <partial name="_ProductCard" model="@prd" />
        }
     </div>

  </div>
</div>

StoreApp/Views/Product/_ProductCard.cshtml
@using StoreApp.Infrastructe.Extensions
@model Product
<div class="col-lg-4 col-md-4 col-sm-12 my-3">
    <div class="card" style="width: 18rem;">
        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.ProductName</h5>
            <p class="card-text">@Model.Price</p>
            <div class="btn btn-group">
                <a class="btn btn-primary" asp-action="Get" asp-route-id="@Model.ProductId">Details</a>
                <form id="@Model.ProductId" asp-page="/cart" method="post">
                    <input type="hidden" asp-for="ProductId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()">
                    <button type="submit" class="btn btn-outline-primary">
                        <i class="fa fa-cart-plus"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>