StoreApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            _cart =cartService;
        }
        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }
    }
    
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
       
        private readonly IServiceManager _serviceManager;

        public ProductSummaryViewComponent(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        //Invoke adı verilmesi zorunlu.
        public string Invoke()
        {
            return _serviceManager.ProductService.GetProducts(false).Count().ToString();
        }

    }
}

StoreApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;


namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetProducts(false);
            return View(model);
        }
        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Store App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-white d-sm-inline-flex justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Product
                        (@await Component.InvokeAsync("ProductSummary"))</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-page="/Contact">Contact</a>
                </li>

            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-area="" asp-page="/Cart">
                        <i class="fa-solid fa-cart-shopping"></i>Cart(@await Component.InvokeAsync("CartSummary"))
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-area="Admin" asp-controller="Dashboard"
                        asp-action="Index">Admin</a>
                </li>
            </ul>

        </div>
    </div>
</nav>